name: Download the File
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Download the file
        run: gh run download ${{ github.event.workflow_run.id }} -n application -D artifact
